name: Build and Push Docker Image

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          cd server  # Change directory to the server folder
          docker build -t bhavyabhutdeveloper/elevator-simulator-server:latest .

      - name: Push Docker image
        run: |
          docker push bhavyabhutdeveloper/elevator-simulator-server:latest
