name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set this in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Set this in GitHub Secrets

      - name: Build Docker image
        run: |
          cd server  # Change directory to the server folder
          docker build -t bhavyabhutdeveloper/elevator-simulator-server:latest .

      - name: Push Docker image
        run: |
          docker push bhavyabhutdeveloper/elevator-simulator-server:latest
